[programs.localnet]
gem_bank = "BanK8PfQ3B1x9fpsm2iP9qFpxwFrgSawyXFUKi5tzfRw"
gem_farm = "FArm7gQCS39qKRTNt6TTqCMKiFuNdZEHN8KVDKZKAT21"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "/Users/vinceweyn/sites/git/gem-farm/GEMjTXQnVcJvetirDQeumniuBkZrAMD1Vvqmvrk3xzdx.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

#[test]
#startup_wait = 100000

[[test.genesis]]
address = "metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s"
program = "./tests/programs/metaplex_token_metadata.so"